### ISSUE TITLE
🚨 Potential Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') (CWE-1321)

### ISSUE THREAD

**Issue by huntr-helper** [mesqueeb/copy-anything#10]
👋 Hello, @mesqueeb - a potential medium severity Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') (CWE-1321) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-mesqueeb/copy-anything** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by jayateertha043** [comment]
Hi incase you feel any difficulty in reproducing thr issue or need more information about fix you can feel free to contact me at https://twitter.com/jayateerthag

**Comment by mesqueeb** [comment]
I don't see how this is relevant to my utility. It all depends on how you use it, whatever the dev copies with copy-anything. Not a real security issue imo. Let me know if otherwise.

**Comment by jayateertha043** [comment]
Hi ,
There were may utilities similar to yours which offered deep copying,cloning and merging functionalities.
I suggest there should always be a check when key is __proto__,prototype and constructor.(This should be a easy fix) as we don't how how anyone is using your package, If someone using your package directly passes user input to copy function it might severely affect their business logic.

Your package is used by many large organizations like less.js, So we don't exactly know how they use it(safely or not).
Most of them directly pass user input without filtering for these keys.

This may cause severe business logic errors.

Here are few report very similar to this which was accepted and fixed by the opensource community: https://huntr.dev/bounties/1-npm-smart-extend/
https://huntr.dev/bounties/1-npm-@livelybone/copy/

Here are few similar reports fixed by our community:
https://github.com/fabiospampinato/plain-object-merge/pull/1
https://github.com/Geta/NestedObjectAssign/pull/11

To know more about Prototype Pollution: https://codeburst.io/what-is-prototype-pollution-49482fc4b638

If you need any other details regarding this , please feel free to contact me in twitter or comment here.

**Comment by mesqueeb** [comment]
@jayateertha043 can you make a PR that would fix the vulnerability ? I can consider releasing it in a major bump.
